# Generated by Django 5.1.4 on 2024-12-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bino_nom', models.CharField(max_length=50)),
                ('asosiy', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Binolar',
            },
        ),
    ]
