# Generated by Django 5.1.4 on 2024-12-14 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonalish_nomi', models.CharField(max_length=255)),
                ('guruh_soni', models.PositiveSmallIntegerField()),
                ('talaba_soni', models.PositiveSmallIntegerField()),
                ('titur_soni', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Yonalishlar',
            },
        ),
        migrations.AlterModelOptions(
            name='bino',
            options={'verbose_name_plural': 'Binolar'},
        ),
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakultet_nomi', models.CharField(max_length=50)),
                ('talabalar_soni', models.PositiveSmallIntegerField()),
                ('guruhlar_soni', models.PositiveSmallIntegerField()),
                ('bino_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bino')),
                ('yonalish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.yonalish')),
            ],
            options={
                'verbose_name_plural': 'Fakultetlar',
            },
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kafedra_nomi', models.CharField(max_length=50)),
                ('kafedra_mudiri', models.CharField(max_length=50)),
                ('oqituvchi_soni', models.PositiveSmallIntegerField()),
                ('fakultet_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.fakultet')),
            ],
            options={
                'verbose_name_plural': 'Kafedralar',
            },
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familya', models.CharField(max_length=50)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('telefon_raqam', models.CharField(max_length=50)),
                ('jinsi', models.BooleanField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=15)),
                ('mutaxasisligi', models.BooleanField(choices=[('Bakalavr', 'Bakalavr'), ('Magister', 'Magister'), ('PHD', 'PHD')], max_length=50)),
                ('mutaxasislik_fani', models.BooleanField(max_length=255)),
                ('kafedra_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kafedra')),
            ],
            options={
                'verbose_name_plural': 'Ustozlar',
            },
        ),
    ]
