# Generated by Django 5.1.4 on 2024-12-14 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_yonalish_alter_bino_options_fakultet_kafedra_ustoz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kafedra_mudiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familya', models.CharField(max_length=255)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('telefon_raqam', models.CharField(max_length=20)),
                ('jinsi', models.BooleanField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Kafedra mudiri',
            },
        ),
        migrations.CreateModel(
            name='Titur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familya', models.CharField(max_length=255)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('telefon_raqam', models.CharField(max_length=20)),
                ('jinsi', models.BooleanField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Titurlar',
            },
        ),
        migrations.AlterField(
            model_name='ustoz',
            name='mutaxasislik_fani',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh_nomi', models.CharField(max_length=15)),
                ('talaba_son', models.PositiveSmallIntegerField()),
                ('yonalish_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.yonalish')),
                ('titur_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.titur')),
            ],
            options={
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.AlterField(
            model_name='kafedra',
            name='kafedra_mudiri',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kafedra_mudiri'),
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familya', models.CharField(max_length=50)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('telefon_raqam', models.CharField(max_length=50)),
                ('jinsi', models.BooleanField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=15)),
                ('guruh_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.guruh')),
            ],
            options={
                'verbose_name_plural': 'Talabalar',
            },
        ),
    ]
