# Generated by Django 5.1.4 on 2024-12-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_kafedra_mudiri_titur_alter_ustoz_mutaxasislik_fani_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakultet',
            name='yonalish',
        ),
        migrations.AddField(
            model_name='fakultet',
            name='yonalish',
            field=models.ManyToManyField(to='main.yonalish'),
        ),
    ]
