# Generated by Django 5.1.4 on 2024-12-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_fakultet_bino_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titur',
            name='jinsi',
            field=models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=15),
        ),
    ]
