# Generated by Django 5.1.4 on 2024-12-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_titur_jinsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafedra_mudiri',
            name='jinsi',
            field=models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=15),
        ),
    ]
