# Generated by Django 5.1.4 on 2024-12-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_kafedra_mudiri_jinsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ustoz',
            name='jinsi',
            field=models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ustoz',
            name='mutaxasisligi',
            field=models.CharField(choices=[('Bakalavr', 'Bakalavr'), ('Magister', 'Magister'), ('PHD', 'PHD')], max_length=50),
        ),
    ]
