# Generated by Django 5.1.4 on 2024-12-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_ustoz_jinsi_alter_ustoz_mutaxasisligi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='jinsi',
            field=models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=15),
        ),
    ]
